In [11]:
import numpy as np
import pandas as pd

print(np.__version__)
print(pd.__version__)


2.5.3
3.0.6


In [12]:
arr = np.array([10, 20, 30, 40, 50])

print(arr)
print(arr * 2)


[10 20 30 40 50]
[ 20  40  60  80 100]


In [13]:
import numpy as np

# Create 1D array and perform operations
arr_1d = np.array([10, 20, 30, 40, 50])
print("Array * 2:", arr_1d * 2)
print("Sum:", arr_1d.sum())
print("1D Slice [1:4]:", arr_1d[1:4])

# Create 2D array and perform indexing/slicing
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Element at (0, 1):", arr_2d[0, 1])
print("2D Slice (all rows, columns 1+):\n", arr_2d[:, 1:])

Array * 2: [ 20  40  60  80 100]
Sum: 150
1D Slice [1:4]: [20 30 40]
2D Element at (0, 1): 2
2D Slice (all rows, columns 1+):
 [[2 3]
 [5 6]]
